name: Pipeline_2
on:
  push:
    branches: [ "hvermaa007-patch-1" ]
  pull_request:
    branches: [ "hvermaa007-patch-1" ]
jobs: 
  Install_Node_Js: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup
      uses: actions/setup-node@v3
      with: 
       node-version: '20'
       
    - name: Debug - List files
      run: |
        echo "📂 Current directory structure:"
        ls -R
        echo "----------------------------------"
      
       
  
