name: Pipleine_2
on:
  push:
    branches: [ "hvermaa007-patch-1" ]
  pull_request:
    branches: [ "hvermaa007-patch-1" ]
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Verify package.json exists
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        if [ ! -f package.json ]; then
          echo "::error::package.json not found in ${{ env.WORKING_DIR }}"
          exit 1
        fi
        echo "Found package.json"

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: ${{ env.WORKING_DIR }}/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', env.WORKING_DIR)) }}
    
    - name: Setup
      uses: actions/setup-node@v3
      with: 
       node-version: '20'
    - name: install dependencies
      run: npm install 

    - name: Run Tests
      run: npm test
       
  
