name: Sample Workflow
on: [push]
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: "Hello"
      run: echo "HI welcome to GitHub"
